[package]
name = "CG-assignment5-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
log = "0.4.17"
simplelog = "0.12.0"
anyhow = "1.0.66"